### ISSUE TITLE
No entity "sensor.afvalwijzer_papier" 

### ISSUE THREAD

**Issue by WilcoKakkenberg** [xirixiz/homeassistant-afvalwijzer#93]
Switching to Home Assistant recently and I'm discovering new integrations.

I would like to integrate afvalwijzer into my HA config.

I have troubles with the "sensor.afvalwijzer_papier". Other sensors are available, only "papier" not.

What could be wrong?

**Comment by xirixiz** [comment]
Not sure, I need your postal code and a random street number in order to verify some things. Could you provide this?

**Comment by WilcoKakkenberg** [comment]
Hi Xirixiz,
Thx for your quick response.
Check your email for postal code details. I rather not share my location details on a public forum.

**Comment by xirixiz** [comment]
Thanks! Tested with your postal code and I see all the data and sensor appear in HASS:
![image](https://user-images.githubusercontent.com/11210639/95001856-60c72d80-05ce-11eb-93b1-e46c84d8dd33.png)

This is the complete data I receive on your postal code and street number. Your township uses different naming, for example ```papiercont``` instead of ```papier```.

Sensor data:
```
{'kerstbomen': 'Geen', 'papiercont': '22-10-2020', 'restafval': '06-10-2020', 'takken': '26-11-2020', 'pmd': '05-10-2020', 'gft': '14-10-2020', 'today': 'Geen', 'first_next_item': 'pmd', 'first_next_in_days': 2, 'tomorrow': 'Geen', 'day_after_tomorrow': 'pmd', 'first_next_date': '05-10-2020'}

Senor entities:
```
['kerstbomen', 'papiercont', 'restafval', 'takken', 'pmd', 'gft', 'today', 'first_next_item', 'first_next_in_days', 'tomorrow', 'day_after_tomorrow', 'first_next_date']
```

So your sensors would be named accordingly, visible in states in the developers section. Hope you have enough info to get things going! Good luck!

**Comment by WilcoKakkenberg** [comment]
thx for the feedback.
I will try to setup friendly names for the sensor entities that I want to change
