### ISSUE TITLE
FR: sensor for 'Nieuws'

### ISSUE THREAD

**Issue by Mariusthvdb** [xirixiz/homeassistant-afvalwijzer#96]
HI

please consider adding a sensor for Nieuws, like we can see in the Saver App:

![cb3df0f0c1ba080ee2070d4a72c25537d063f61d](https://user-images.githubusercontent.com/33354141/95561271-c37b5780-0a1a-11eb-9ecc-396a03e4d375.jpeg)

![20201009_083600000_iOS](https://user-images.githubusercontent.com/33354141/95561679-5f0cc800-0a1b-11eb-8b4e-38bdf14126f1.jpg)

would be really nice to have a (binary) sensor for new news being published, and be able to create a (persistent) notification based on that. Of course with the full message in its attributes, so we can show that easily eg in a markdown card.

thanks for considering

**Comment by xirixiz** [comment]
This is a nice addition, and next week I`ll try to implement it. It shouldn't be hard.

**Comment by xirixiz** [comment]
I created some code to parse the news but I also noticed multiple news items may persist. So when the case is that there are 5 news items, 5 new sensors will be created. Besides that the code differs for each provider, so it'll cause really messy code. I decided to leave it out for now, but I created a branch for further development. Maybe in the future I think otherwise.
